import { Metadata } from "next";
import "../assets/scss/main.scss";
import Header from "@/src/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="o-container">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
